version: 0.2

phases:
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 502935699135.dkr.ecr.us-east-1.amazonaws.com
      
            
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
      - mv target/ROOT.war ROOT.war
      - docker build -t pritam .
      - docker tag pritam:latest 502935699135.dkr.ecr.us-east-1.amazonaws.com/pritam:latest
                 
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push 502935699135.dkr.ecr.us-east-1.amazonaws.com/pritam:latest
      -  printf'[{"name":"pritam","imageUri":"502935699135.dkr.ecr.us-east-1.amazonaws.com/pritamt"}]' > imagedefinition.json
      
     
artifacts:
  files:
    - 'target/*.war'
    -  imagedefinition.json
  discard-paths: yes
